sudo: false
language: python
python:
  - "3.4"
before_install: apt-get install telnet
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
 - sim/telserver.py sim.cfg &
 - nosetests src/pyco/test/unit/test_fake.py